name: Deploy

on:
  workflow_dispatch:
permissions:
  contents: write
env:
  MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
  
jobs:
  deploy:
    uses: RobertoVillalon/infraestructura/.github/workflows/deployAngularToGithubPages.yml@main
    with:
      working_directory: "."
      base_href: "/maps/"
      publish_dir: "./dist/maps/browser"
      environments_variables: |
        {
          production: true,
          mapboxKey: $MAPBOX_TOKEN
        }
