name: Deploy

on:
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  deploy:
    uses: RobertoVillalon/infraestructura/.github/workflows/deployAngularToGithubPages.yml@main
    secrets: inherit
    with:
      base_href: "/maps-app/"
      publish_dir: "./dist/maps-app/browser"
      environment_keys: "MAPBOX_TOKEN"
